### PR TITLE
created a new object to hold results

### PR DESCRIPTION
**Pull request by dbfreem**
Hey, I created a new object to hold the results that were returned based on a TODO I found in the code. It allows for some of the results operations to be pulled out of the fetcher.lib and put into a Result class. This class can currently generate a pandas dataframe and write to a csv file. I feel like there is a lot of opportunity to expand/refactor this object but it was mainly just copy and pasted from the fetcher.lib for now until I checked to see if it's something you are interested in moving forward with.

### CODE REVIEW

**Comment by dbfreem** [comment]
not sure why flake8 is complaining about fetcher/extras/backfill.py. I initially didn't change that file. After there error I modified the docstring trying to fix the flake8 error with no success. Locally flake8 does not complain about this file.

**Comment by space-buzzer** [comment]
> not sure why flake8 is complaining about fetcher/extras/backfill.py. I initially didn't change that file. After there error I modified the docstring trying to fix the flake8 error with no success. Locally flake8 does not complain about this file.

I pushed `backfill.py` last night accidentally. Shouldn't have

**Comment by space-buzzer** [comment]
Hi, thanks!
If you don't mind to wait a bit longer, I'll check this tomorrow morning

**Comment by dbfreem** [comment]
I was actually thinking about this some more. It might even make sense to create a directory under fetcher called release. This folder could hold the release object and things like push_to_sheets or other functions.

**Comment by space-buzzer** [comment]
Re: `push_to_spreadsheet` it's used for other files too right now, not just the fetches, so `tools` fits better for now. I have a couple of other spreadsheet helpers that will go with it soon.

I think we can definitely extract all the `DataFrame` handling into its own class.
The class can be simplified and it should encapsulate all the options regarding the data frame.
Specifically:
- It doesn't need to extend `dict`, and the aggregation of items can happen at append time
- All the configuration that's passed to `write_to_csv` and `get_dataframe` can be part of the class
- Currently, because of the structure of `write_to_csv` and `get_dataframe` the dataframe is built twice, once for each method. This should be compacted.


I want to introduce a small config change that can make part of the current control flow and parameters redundant.

**Comment by dbfreem** [comment]
Thanks for the feedback that makes perfect sense.

**Comment by dbfreem** [comment]
@space-buzzer here is my latest based on your feedback. Let me know what you think. A couple of items to note

- When you append to the Result object it adds the data to the internal dictionary and sets a flag that the dataframe needs to be regenerated. The thought here is reading happens much less than writing so only generate the dataframe if it isn't already generated when the dataframe property is accessed.
-In the fetcher I changed the method signature of the fetch_all method to fetch_states and added a states parameter. The thought here was that it made one main entry point into the fetcher to get states instead of two. I also marked fetch state as private since you can go through fetch_states and just pass a state now. This made it easier to maintain the results in one place of the fetcher.

Let me know what your thoughts are.

**Comment by dbfreem** [comment]
@space-buzzer hey I noticed several changes that had been made that put this PR in conflict now. Would you like me to rework this to incorporate your changes to lib.py or do you want to just leave the results implementation in lib.py the way it is now. Either way works for me just trying to figure out where I could help.

**Comment by dbfreem** [comment]
This PR is in conflict now. Closing.

**Pull request closed without merging**
