### PR TITLE
[AZ] Add POSITIVE and DEATH to races

### PR DESCRIPTION
**Pull request by alxmjo**
Didn't realize that AZ uses Tableau for race/ethnicity data until I'd already added in positives and deaths so race/ethnicity will come after I've figured out what to do with Tableau.

### CODE REVIEW

**Comment by space-buzzer** [comment]
For the normal numbers (e.g., cases & death), should you fetch it or should we take it from the states auto-fetcher or directly from WS2?

**Comment by alxmjo** [comment]
> For the normal numbers (e.g., cases & death), should you fetch it or should we take it from the states auto-fetcher or directly from WS2?

Good question. My thinking in fetching directly was twofold: 

1. These numbers are likely to be more up to date than (race's version of) WS2, as those numbers are only updated on Wednesdays and Sundays.
2. It's my understanding that if I run the script with `dataset=races` then I'm not actually running the normal states auto-fetcher and so cannot use these values. Perhaps I'm mistaken.

**Comment by space-buzzer** [comment]
> It's my understanding that if I run the script with dataset=races then I'm not actually running the normal states auto-fetcher and so cannot use these values. Perhaps I'm mistaken
This is true

I was thinking of WS2 that's used by main DE pub shift (or the public sheet itself).
If you see that it requires too much maintenance -- that's already done for DE pub shift. I'm worried about extra maintenance, because we already maintain it for pub shift. But we can see how it goes.

Can you remove the merge you added, it merges in the other commits and there's a conflict and GitHub won't rebase it nicely

**Comment by alxmjo** [comment]
Okay, done. Sorry about that. I will pay attention to the maintenance and rewrite if it becomes an issue.

**Comment by space-buzzer** [comment]
Merged with `--ff-only` and pushed

**Pull request closed without merging**
